# Generated by Django 3.0.7 on 2020-06-05 12:36

import blog_posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('bpost', models.Field(validators=[blog_posts.models.bpost_validate])),
            ],
            options={
                'verbose_name_plural': 'post',
                'db_table': 'post',
            },
        ),
    ]
